name: Run Python Tests        #tên workflows

on:                           #khi nào chạy
  push:                       #chạy khi có push 
  pull_request:               #chạy khi tạo pull request

jobs:
  test:                       #tên job
    runs-on: ubuntu-latest    #môi trường chạy(máy ảo)

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  #bước lấy mã nguồn

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-html

    - name: Run tests
      run: |
        pytest -v --html=report.html --self-contained-html

    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: Test Report
        path: report.html
